config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "battles#index"
resources :index, only: [:index]
resources :users, only: [:edit, :update]
resources :battles, only: [:index, :new, :create, :destroy] do
  collection do
    get 'search'
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
class Battle < ApplicationRecord
  belongs_to :user
  validates :text,:answer, length: { in: 1..20 }
  def self.search(search)
    if search
      Battle.where('text LIKE(?)', "%#{search}%")
    else
      Battle.all
    end
  end
end

app/models/battler.rb
class Battler < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :battles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/battlers_controller.rb
class BattlersController < ApplicationController
  def index
    monster = ['スライム', 'ゴブリン', 'ゴーレム', '魔王の側近', '魔王', '姫']
    @monster = monster[rand(5)]
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def index
    @battles = Battle.all
    @battle = Battle.new
    
  end
  def new
    @battle = Battle.new
  end
  def create
    Battle.create(battle_params)
    @battle = Battle.new(battle_params)
    respond_to do |format|
    format.html { redirect_to :root }
    format.json 
    end
  end
  def destroy
    battle = Battle.find(params[:id])
    battle.destroy
     redirect_to :root
  end
  def search
    @battles = Battle.search(params[:keyword])
  end
  private
  def battle_params
    params.require(:battle).permit(:text, :answer)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :detect_devise_variant  # 何でも良い?? --- (1)

  def index
  end

  private
      def detect_devise_variant  # (1)と同じ名前
          case request.user_agent
          when /iPad/
              request.variant = :tablet
          when /iPhone/
              request.variant = :mobile
          end
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battle_helper.rb
module BattleHelper
end

app/helpers/battlers_helper.rb
module BattlersHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/battles/_battle.html.haml
.body
  .battle-message
    =link_to "/battles/#{battle.id}", method: :delete, class: "message-delete" do
      = icon('fas', 'trash-alt')
    .message-all
      .message-text
        .message-text__inline
          Q.
          =battle.text
      .message-answer
        .message-answer__inline
          A.
          =battle.answer
        
  

app/views/battles/index.html.haml
.body
  .header
    
    計
    =@battles.count
    問
  .main
    .left-bar
      .player-zone
        .player-zone__name
        単語張
        .player-zone__date
          
        .player-zone__battle-select
          .form
            =form_with model: @battle, local: true, id: "making" do |form|
              =form.text_field :text, placeholder: "問題（最大18字）", class: "question-message"
              =form.text_field :answer, placeholder: "答え（最大18字）", class: "answer-message"
              =form.submit type:"submit", value:"作成", class: "submit-btn"
    .right-bar
      .monster-zone
        .watch
          /=image_tag "dial.png", class:"clock"
          /=image_tag "hour.png", id:"hour", class:"clock"
          /=image_tag "minute.png", id:":minute", class:"clock"
          / =image_tag "second.png", id:"second", class:"clock"
        .form_search
          =form_with url: search_battles_path, local: true, method: :get, class: "search-form" do |form|
            =form.text_field :keyword, placeholder: "問題を検索", class: "search"
            =form.submit type:"submit", value:"検索", class: "search-btn"
        .form_style-change
          =form_with class: "style-form" do |form|
            =form.submit type:"submit", value:"切替", class: "style-btn"
        
    .battles
      .battle-field
        .messages
          = render @battles
      .footer
        ©2019 Tetsuya Omoto

app/views/battles/search.html.haml
.body
  .header
    
    計
    =@battles.count
    問
  .main
    .left-bar
      .player-zone
        .player-zone__name
        単語張
        .player-zone__date
          
        .player-zone__battle-select
          .form
            =form_with model: @battle, local: true, id: "making" do |form|
              =form.text_field :text, placeholder: "問題（最大18字）", class: "question-message"
              =form.text_field :answer, placeholder: "答え（最大18字）", class: "answer-message"
              =form.submit type:"submit", value:"作成", class: "submit-btn"
              //=form.submit type:"submit", value:"必殺技", class: "supercial"
              //=form.submit type:"submit", value:"防御", class: "defence"
    .right-bar
      .monster-zone
        .watch
          /=image_tag "dial.png", class:"clock"
          /=image_tag "hour.png", id:"hour", class:"clock"
          /=image_tag "minute.png", id:":minute", class:"clock"
          / =image_tag "second.png", id:"second", class:"clock"
        .form_search
          =form_with url: search_battles_path, local: true, method: :get, class: "search-form" do |form|
            =form.text_field :keyword, placeholder: "問題を検索", class: "search"
            =form.submit type:"submit", value:"検索", class: "search-btn"
        .form_style-change
          =form_with class: "style-form" do |form|
            =form.submit type:"submit", value:"切替", class: "style-btn"
        
    .battles
      .battle-field
        .messages
          = render @battles
      .footer
        ©2019 Tetsuya Omoto

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RpgChat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "https://cdn.jsdelivr.net/npm/bubbly-bg@1.0.0/dist/bubbly-bg.js"
  %body
    = yield